CLUSTALW mCherry2.XX, mCherry2.25, mCherry2.75, mCherry2.90

mCherry2.XX   ATGGTGAGCAAGGGCGAGGAGGATAACCTGGCCATCATCAAGGAGTTTATGCGGTTTAAG 60
mCherry2.25   ATGGTGAGCAAGGGCGAGGAGGATAACCTGGCCATCATCAAGGAGTTCATGAGATTTAAG 60
mCherry2.50   ATGGTGAGCAAGGGCGAGGAGGATAACCTGGCCATCATCAAGGAGTTCATGAGATTCAAG 60
mCherry2.75   ATGGTGAGCAAGGGCGAGGAGGATAACCTGGCCATCATCAAGGAGTTCATGCGCTTCAAG 60
mCherry2.90   ATGGTGAGCAAGGGCGAGGAGGATAACCTGGCCATCATCAAGGAATTCATGCGTTTCAAA 60
              ******************************************** ** *** * ** ** 

mCherry2.XX   GTGCATATGGAGGGGAGTGTGAATGGACATGAGTTCGAGATCGAGGGGGAGGGAGAGGGC 120
mCherry2.25   GTGCATATGGAGGGCTCAGTGAATGGCCACGAGTTTGAGATTGAGGGCGAGGGCGAGGGG 120
mCherry2.50   GTGCACATGGAGGGCTCCGTGAACGGCCATGAGTTCGAGATCGAGGGCGAGGGCGAGGGC 120
mCherry2.75   GTGCACATGGAGGGCTCCGTGAACGGCCACGAGTTCGAAATCGAAGGCGAGGGCGAGGGC 120
mCherry2.90   GTCCACATGGAGGGTTCTGTAAACGGCCACGAATTCGAAATCGAAGGTGAAGGTGAAGGT 120
              ** ** ********    ** ** ** ** ** ** ** ** ** ** ** ** ** ** 

mCherry2.XX   AGACCCTATGAGGGAACACAAACGGCCAAGTTGAAGGTGACGAAGGGTGGACCCTTGCCC 180
mCherry2.25   CGCCCCTATGAGGGCACACAAACAGCCAAGTTGAAGGTGACCAAGGGAGGGCCCTTACCC 180
mCherry2.50   CGCCCCTATGAGGGCACACAGACCGCCAAGCTTAAGGTGACAAAGGGTGGCCCCCTGCCC 180
mCherry2.75   CGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGTGGCCCCCTGCCC 180
mCherry2.90   CGTCCGTACGAAGGCACTCAGACTGCTAAGCTGAAAGTTACCAAAGGCGGTCCGCTGCCG 180
               * ** ** ** ** ** ** ** ** *** * ** ** ** ** ** ** **  * ** 

mCherry2.XX   TTTGCCTGGGATATTCTCAGTCCTCAATTTATGTATGGGAGCAAGGCCTATGTGAAGCAT 240
mCherry2.25   TTCGCCTGGGATATATTGTCACCTCAATTTATGTATGGGTCGAAGGCCTATGTGAAGCAC 240
mCherry2.50   TTCGCCTGGGACATACTGAGTCCTCAGTTCATGTACGGCTCCAAGGCCTACGTGAAGCAC 240
mCherry2.75   TTCGCTTGGGACATCCTGTCCCCTCAGTTCATGTACGGCTCCAAGGCCTACGTGAAGCAC 240
mCherry2.90   TTCGCTTGGGACATCCTGTCCCCGCAGTTCATGTACGGTTCCAAAGCTTACGTAAAGCAC 240
              ** ** ***** **  *    ** ** ** ***** **    ** ** ** ** ***** 

mCherry2.XX   CCCGCCGACATACCCGATTACTTGAAGTTGAGTTTTCCCGAGGGGTTTAATTGGGAGAGG 300
mCherry2.25   CCCGCCGATATCCCCGACTACTTGAAGCTGTCATTTCCCGAGGGGTTTAATTGGGAGCGG 300
mCherry2.50   CCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTTAATTGGGAGCGC 300
mCherry2.75   CCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTCAATTGGGAGCGC 300
mCherry2.90   CCGGCCGACATACCGGACTACCTAAAGTTGTCTTTCCCGGAAGGTTTCAACTGGGAACGC 300
              ** ***** ** ** ** *** * *** **   ** ** ** ** ** ** *****  * 

mCherry2.XX   GTGATGAATTTTGAGGATGGCGGGGTGGTGACCGTGACCCAGGATTCAAGTCTTCAAGAT 360
mCherry2.25   GTGATGAATTTCGAGGACGGCGGGGTGGTGACCGTGACCCAAGATAGTAGTCTGCAAGAT 360
mCherry2.50   GTGATGAACTTCGAGGACGGCGGCGTGGTGACCGTGACCCAGGACTCCTCCCTGCAGGAC 360
mCherry2.75   GTAATGAACTTCGAAGACGGCGGCGTGGTGACCGTTACCCAGGACTCCTCCCTGCAGGAC 360
mCherry2.90   GTTATGAACTTCGAAGACGGCGGCGTTGTCACTGTAACTCAGGACTCTTCTTTACAGGAC 360
              ** ***** ** ** ** ***** ** ** ** ** ** ** **        * ** ** 

mCherry2.XX   GGCGAGTTTATATATAAGGTGAAGTTACGAGGGACAAATTTTCCCAGCGATGGACCCGTA 420
mCherry2.25   GGCGAGTTTATATATAAGGTGAAGTTGAGAGGAACCAATTTCCCCTCGGACGGCCCCGTG 420
mCherry2.50   GGCGAGTTTATCTACAAGGTGAAGCTGCGCGGCACCAACTTCCCCTCCGATGGACCCGTA 420
mCherry2.75   GGCGAGTTCATCTACAAGGTGAAGCTGCGCGGCACCAACTTCCCCTCCGACGGCCCCGTA 420
mCherry2.90   GGTGAATTCATCTACAAGGTAAAGCTGCGCGGTACCAACTTCCCTTCTGACGGTCCGGTA 420
              ** ** ** ** ** ***** *** *  * ** ** ** ** **    ** ** ** ** 

mCherry2.XX   ATGCAATGTCGAACCATGGGGTGGGAGGCCTCGACAGAGCGGATGTACCCCGAGGATGGA 480
mCherry2.25   ATGCAATGTAGGACAATGGGCTGGGAGGCCAGCACTGAGCGGATGTATCCCGAGGACGGA 480
mCherry2.50   ATGCAGTGTAGAACAATGGGATGGGAGGCCTCCACAGAGCGGATGTACCCCGAGGACGGC 480
mCherry2.75   ATGCAGTGCCGTACCATGGGCTGGGAAGCTTCCACTGAACGGATGTACCCCGAGGACGGC 480
mCherry2.90   ATGCAGTGCCGTACTATGGGCTGGGAAGCTTCTACCGAAAGGATGTACCCGGAAGACGGT 480
              ***** **  * ** ***** ***** **    ** **  ******* ** ** ** ** 

mCherry2.XX   GCCTTGAAGGGAGAGATTAAGCAAAGGCTTAAGTTAAAGGATGGGGGACATTATGATGCC 540
mCherry2.25   GCCTTAAAGGGAGAGATCAAGCAGAGGCTGAAGCTTAAGGACGGAGGGCATTACGACGCC 540
mCherry2.50   GCCCTGAAGGGGGAGATCAAGCAGAGGTTGAAGCTTAAGGACGGGGGCCACTACGACGCT 540
mCherry2.75   GCCCTGAAGGGCGAGATCAAGCAGAGGCTGAAGCTGAAGGACGGCGGCCACTACGACGCT 540
mCherry2.90   GCTCTGAAAGGTGAAATCAAGCAGCGTTTAAAGCTGAAGGACGGCGGCCACTACGACGCT 540
              **  * ** ** ** ** *****  *  * *** * ***** ** ** ** ** ** ** 

mCherry2.XX   GAGGTCAAGACGACATATAAGGCCAAGAAGCCCGTGCAACTACCCGGAGCCTATAATGTC 600
mCherry2.25   GAGGTCAAGACAACCTACAAGGCCAAGAAGCCCGTGCAATTGCCCGGCGCCTATAATGTC 600
mCherry2.50   GAGGTCAAGACCACCTACAAGGCCAAGAAGCCCGTGCAACTGCCCGGGGCCTACAACGTC 600
mCherry2.75   GAAGTCAAGACCACCTACAAGGCCAAGAAGCCCGTTCAGCTGCCGGGCGCCTACAACGTC 600
mCherry2.90   GAAGTTAAGACCACTTACAAAGCTAAGAAACCGGTTCAGCTGCCGGGCGCTTACAACGTT 600
              ** ** ***** ** ** ** ** ***** ** ** **  * ** ** ** ** ** ** 

mCherry2.XX   GATATAAAGTTGGATATACTTTCGCATAATGAGGACTATACGATTGTGGAACAATATGAG 660
mCherry2.25   GATATCAAGTTGGATATTCTTTCCCACAATGAGGACTATACCATCGTGGAACAGTACGAG 660
mCherry2.50   GACATCAAGTTGGACATCCTTAGTCACAACGAGGACTACACCATCGTGGAGCAATATGAG 660
mCherry2.75   GACATCAAGCTGGACATCCTTTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAA 660
mCherry2.90   GACATCAAGCTGGACATCCTGTCTCACAACGAAGACTACACTATCGTTGAACAGTACGAA 660
              ** ** *** **** ** **    ** ** ** ***** ** ** ** ** ** ** ** 

mCherry2.XX   CGGGCCGAGGGGCGGCATAGCACGGGAGGGATGGATGAGCTTTACAAG 708
mCherry2.25   CGGGCCGAGGGAAGGCATAGTACAGGCGGCATGGATGAGCTCTATAAG 708
mCherry2.50   CGCGCCGAGGGAAGGCATTCCACCGGCGGCATGGACGAGTTATACAAG 708
mCherry2.75   CGCGCTGAAGGCCGCCACTCCACCGGCGGCATGGACGAACTGTACAAG 708
mCherry2.90   CGTGCTGAAGGTCGTCACAGTACTGGCGGCATGGACGAATTGTATAAG 708
              ** ** ** **  * **    ** ** ** ***** **  * ** ***
