CLUSTAL W (1.81) multiple sequence alignment

gene02          ATGCTAGAATATGCTCTGAG--ATATTCAATATATCGTGCTAGGATATGCTCTGAGATAT
gene01          ATGCRAGGATATGCTCTGAGATATATTCTATATATCGTGCTAGGATATGCTCTGAGATAT
gene03          ATGCT---ACATGCTCTGAGACATATTCTATATATCGTGCTAGG---TGCTCTGAGATAT
                ****    * **********  ****** ***************   *************

gene02          ANNCTAGATATCGGCTAGGATATGTTCTGAGATATATTCTTTTATATCG
gene01          ATTCTATATATCGGCTAGGATATGCTCTGAGATATATTC-TATATATCG
gene03          ATTCTATATATCGGCTAGGATATGCTCTGAGATATATTC-TATATATCG
                *  *** ***************** ************** * *******
